kmyk/Jikka

CHANGELOG.md
package.yaml

because it's still WIP and the majar version should be zero.

chore: Fix the version to v5.0.2.0

---

examples/data/abc134_c.medium.generator.py

ci: Reduce the sizes of inputs of examples/abc134_c.py

---

src/Jikka/Core/Convert.hs
src/Jikka/Core/Convert/ArithmeticalExpr.hs
src/Jikka/Core/Language/ArithmeticalExpr.hs
src/Jikka/Core/Language/Util.hs
test/Jikka/Core/Language/ArithmeticalExprSpec.hs

Arithmetical expr

---

src/Jikka/CPlusPlus/Convert/AddMain.hs
src/Jikka/CPlusPlus/Convert/FromCore.hs
src/Jikka/CPlusPlus/Format.hs
src/Jikka/CPlusPlus/Language/Util.hs
src/Jikka/Common/Alpha.hs
src/Jikka/Core/Convert/ConstantPropagation.hs
src/Jikka/Core/Language/Util.hs
src/Jikka/Main/Subcommand/Convert.hs
test/Jikka/CPlusPlus/Convert/FromCoreSpec.hs
test/Jikka/CPlusPlus/FormatSpec.hs

Make generated C++ code cleaner

---

src/Jikka/Core/Convert/Alpha.hs
src/Jikka/Core/Convert/ArithmeticalExpr.hs
src/Jikka/Core/Convert/Beta.hs
src/Jikka/Core/Convert/BubbleLet.hs
src/Jikka/Core/Convert/CloseAll.hs
src/Jikka/Core/Convert/CloseMin.hs
src/Jikka/Core/Convert/CloseSum.hs
src/Jikka/Core/Convert/CumulativeSum.hs
src/Jikka/Core/Convert/Eta.hs
src/Jikka/Core/Convert/MakeScanl.hs
src/Jikka/Core/Convert/ShortCutFusion.hs
src/Jikka/Core/Convert/SpecializeFoldl.hs
src/Jikka/Core/Convert/TypeInfer.hs

docs: Write documents for `Jikka.Core.Convert.*` modules

---

docs/language.ja.md
docs/language.md
examples/abc127_e.py
src/Jikka/RestrictedPython/Convert/ResolveBuiltin.hs
src/Jikka/RestrictedPython/Language/Builtin.hs
test/Jikka/RestrictedPython/Language/BuiltinSpec.hs

feat(rpython): Move some builtin functions to jikka module

---

examples/README.md
examples/data/dp_b.large.generator.py
examples/data/dp_b.large.solver.py
src/Jikka/CPlusPlus/Convert.hs
src/Jikka/CPlusPlus/Convert/AddMain.hs
src/Jikka/CPlusPlus/Convert/MoveSemantics.hs
src/Jikka/CPlusPlus/Language/Util.hs

feat(cxx): Replace unnecessary copy with move

---

scripts/integration_tests.py

test: Use the standard Python for testing

---

docs/language.ja.md
docs/language.md
examples/yukicoder_1618.py
src/Jikka/Python/Convert/ToRestrictedPython.hs
src/Jikka/Python/Parse/Happy.y
src/Jikka/RestrictedPython/Convert.hs
src/Jikka/RestrictedPython/Convert/Alpha.hs
src/Jikka/RestrictedPython/Convert/ParseMain.hs
src/Jikka/RestrictedPython/Convert/ResolveBuiltin.hs
src/Jikka/RestrictedPython/Convert/ToCore.hs
src/Jikka/RestrictedPython/Convert/TypeInfer.hs
src/Jikka/RestrictedPython/Convert/UseAppend.hs
src/Jikka/RestrictedPython/Evaluate.hs
src/Jikka/RestrictedPython/Format.hs
src/Jikka/RestrictedPython/Language/Expr.hs
src/Jikka/RestrictedPython/Language/Util.hs

Allow some syntax in Python

---

.gitignore
CHANGELOG.md
Jikka.cabal
package.yaml

Upload to Hackage

---

Jikka.cabal
package.yaml

cabal gen-bounds したのに cabal install できない、なんでや

build: Increase the bound of base

---

docs/internal.ja.md

[fix] typo

---

src/Jikka/Core/Convert/StrengthReduction.hs
src/Jikka/Core/Language/ArithmeticalExpr.hs

https://github.com/kmyk/Jikka/discussions/24#discussioncomment-1128713

fix(core) : arithmetical expr bug

---

Jikka.cabal
src/Jikka/Core/Convert.hs
src/Jikka/Core/Convert/EqualitySolving.hs

close #126 
特にList周りについて合ってるのか不安なのですが、一人で悩んでも埒が明かなそうなのでpull requestとして投げさせて頂きました。

Add Jikka.Core.Convert.EqualitySolving

---

examples/wip/abc200_b.py
examples/wip/abc203_b.py
examples/wip/abc204_b.py
examples/wip/abc206_b.py
examples/wip/abc207_b.py
examples/wip/abc208_b.py

AtCoder ABC 200 - 212 のB問題のうち、文字列出力など仕様上 v5.1.0.0 で対象ではないと思われる問題を除外して、6問のサンプルを追加しました
#141

Add some AtCoder ABC-B examples to `examples/wip`

---

scripts/add_test_cases.py

chore: Add scripts/add_test_cases.py

---

Jikka.cabal
src/Jikka/CPlusPlus/Convert/UnpackTuples.hs
test/Jikka/CPlusPlus/Convert/MoveSemanticsSpec.hs
test/Jikka/CPlusPlus/Convert/UnpackTuplesSpec.hs

#153 の調査の過程で足した unit tests たちです (まだ調査終わってないけど……)
cc @riantkb
C++ の構文木のノードを直書きするのしんどいし C++ のパーサがほしい。後で書きます

Add tests around #153

---

src/Jikka/CPlusPlus/Language/Expr.hs

docs(cxx): Add comments to src/Jikka/CPlusPlus/Language/Expr.hs

---

src/Jikka/Core/Convert/CloseAll.hs
src/Jikka/Core/Language/Expr.hs

Fix bugs of Jikka.Core.Convert.CloseAll

---

examples/dp_z-kubaru.py
examples/dp_z-morau.py
src/Jikka/CPlusPlus/Convert/FromCore.hs
src/Jikka/CPlusPlus/Convert/MoveSemantics.hs
src/Jikka/CPlusPlus/Convert/UnpackTuples.hs
src/Jikka/CPlusPlus/Format.hs
src/Jikka/CPlusPlus/Language/Expr.hs
src/Jikka/CPlusPlus/Language/Util.hs
src/Jikka/Core/Convert/ANormal.hs
src/Jikka/Core/Convert/Alpha.hs
src/Jikka/Core/Convert/ConstantPropagation.hs
src/Jikka/Core/Convert/KubaruToMorau.hs
src/Jikka/Core/Convert/MakeScanl.hs
src/Jikka/Core/Convert/RemoveUnusedVars.hs
src/Jikka/Core/Convert/SegmentTree.hs
src/Jikka/Core/Convert/TrivialLetElimination.hs
src/Jikka/Core/Convert/TypeInfer.hs
src/Jikka/Core/Evaluate.hs
src/Jikka/Core/Format.hs
src/Jikka/Core/Language/Beta.hs
src/Jikka/Core/Language/Expr.hs
src/Jikka/Core/Language/FreeVars.hs
src/Jikka/Core/Language/QuasiRules.hs
src/Jikka/Core/Language/RewriteRules.hs
src/Jikka/Core/Language/TypeCheck.hs
src/Jikka/Core/Language/Util.hs
src/Jikka/Core/Parse/Alex.x
src/Jikka/Core/Parse/Happy.y
src/Jikka/Core/Parse/Token.hs
src/Jikka/RestrictedPython/Convert/ToCore.hs

Use assertions in core and C++

---

scripts/add_test_cases.py

とってきたファイル名が `.out` になっていなかったので直しました

Fix filename in scripts/add_test_cases.py

---

runtime/include/jikka/segment_tree.hpp
src/Jikka/CPlusPlus/Convert/FromCore.hs
src/Jikka/CPlusPlus/Format.hs
src/Jikka/CPlusPlus/Language/Expr.hs
src/Jikka/Core/Convert/CumulativeSum.hs
src/Jikka/Core/Convert/SegmentTree.hs
src/Jikka/Core/Convert/SpecializeFoldl.hs
src/Jikka/Core/Evaluate.hs
src/Jikka/Core/Format.hs
src/Jikka/Core/Language/BuiltinPatterns.hs
src/Jikka/Core/Language/Expr.hs
src/Jikka/Core/Language/TypeCheck.hs
src/Jikka/Core/Language/Util.hs

chore: Merge #163

---

CHANGELOG.md
Jikka.cabal
package.yaml

もらってたプルリクがぜんぶマージされたので、ここらでバージョン番号を上げておく
cc @hotman78 @riantkb @rsk0315 @uta8a @zer0-star

chore: v5.2.0.0

---

src/Jikka/CPlusPlus/Convert/AddMain.hs
src/Jikka/CPlusPlus/Convert/BurnFlavouredNames.hs
src/Jikka/CPlusPlus/Convert/FromCore.hs
src/Jikka/CPlusPlus/Convert/InlineSetAt.hs
src/Jikka/CPlusPlus/Convert/UnpackTuples.hs
src/Jikka/CPlusPlus/Language/Expr.hs
src/Jikka/CPlusPlus/Language/Util.hs
src/Jikka/Common/Name.hs
src/Jikka/Python/Convert/ToRestrictedPython.hs
src/Jikka/RestrictedPython/Convert/Alpha.hs
src/Jikka/RestrictedPython/Convert/DefaultMain.hs
src/Jikka/RestrictedPython/Convert/ParseMain.hs
src/Jikka/RestrictedPython/Convert/ToCore.hs
src/Jikka/RestrictedPython/Evaluate.hs
src/Jikka/RestrictedPython/Language/Builtin.hs
src/Jikka/RestrictedPython/Language/Expr.hs
src/Jikka/RestrictedPython/Language/Util.hs

refactor(rpython): Put name hints to names of restricted Python
